- name: Ping hosts
  ansible.builtin.ping:

- name: Confirm
  ansible.builtin.pause:
    prompt: "Are you sure you want te perform a factory reset?"
  register: confirm_factory_reset
  # delegate_to: localhost

- name: Perform a factory reset
  ansible.builtin.shell:
    cmd: /etc/init.d/S58factoryreset reset
    poll: 0
  when: confirm_factory_reset.user_input | bool
