- name: Install pexpect python extension
  ansible.builtin.pip:
    name: pexpect

- name: Install Moonraker and Nginx
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "1\\) Install Moonraker and Nginx": "1"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Install Fluidd (port 4408)
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "2\\) Install Fluidd": "2"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Install Entware
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "4\\) Install Entware": "4"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: OPKG update
  ansible.builtin.shell:
    cmd: opkg update
  changed_when: false

- name: Install Klipper Gcode Shell Command
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "5\\) Install Klipper Gcode Shell Command": "5"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Install Klipper Adaptive Meshing & Purging
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "6\\) Install Klipper Adaptive Meshing & Purging": "6"
      "Are you sure you want to install": "y"
      "Do you want to enable needed macros for PrusaSlicer": "n"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Install Buzzer Support
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "7\\) Install Buzzer Support": "7"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Install Nozzle Cleaning Fan Control
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "8\\) Install Nozzle Cleaning Fan Control": "8"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Install Fans Control Macros
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "9\\) Install Fans Control Macros": "9"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Install Improved Shapers Calibrations
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "10\\) Install Improved Shapers Calibrations": "10"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Install Useful Macros
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "11\\) Install Useful Macros": "11"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Install Save Z-Offset Macros
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "12\\) Install Save Z-Offset Macros": "12"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Install M600 Support
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "14\\) Install M600 Support": "14"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Install Moonraker Timelapse
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "16\\) Install Moonraker Timelapse": "16"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Install USB Camera Support
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "18\\) Install USB Camera Support": "18"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Install Mobileraker Companion
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "1\\) \\[Install\\] Menu": "1"
      "22\\) Install Mobileraker Companion": "22"
      "Are you sure you want to install": "y"
      "installed successfully": "q"
      "already installed": "q"
  register: cmd_result
  changed_when: '"already installed" not in cmd_result.stdout'

- name: Enable camera settings in Moonraker
  ansible.builtin.expect:
    command: sh /usr/data/helper-script/helper.sh
    echo: true
    timeout: 600
    responses:
      "5\\) \\[Tools\\] Menu": "5"
      "4\\) Enable camera settings in Moonraker": "4"
      "want to enable": "y"
      "have been enabled": "q"
      "alredy enabled": "q"
  register: cmd_result
  changed_when: '"alredy enabled" not in cmd_result.stdout'
